variables:
  build.buildNumber: $(Date:yyyyMMdd)$(Rev:.rr)
  build.configuration: Release
  build.projectName: TCDFx.Tools.DogGen

name: $(build.buildNumber)

resources:
  - repo: self

trigger:
  - master

- job: macOS
  pool:
    vmImage: 'macOS-10.13'

  steps:
  - script: |
      dotnet restore --no-dependencies --disable-parallel --force
      dotnet build -c $(configuration) --no-restore --no-dependencies --version-suffix $(build.buildNumber)

    workingDirectory: tools\$(build.projectName)
    displayName: Build

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - script: |
      dotnet restore --no-dependencies --disable-parallel --force
      dotnet build -c $(configuration) --no-restore --no-dependencies --version-suffix $(build.buildNumber)

    workingDirectory: tools\$(build.projectName)
    displayName: Build

- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'

  steps:
  - script: |
      dotnet restore --no-dependencies --disable-parallel --force
      dotnet build -c $(configuration) --no-restore --no-dependencies --version-suffix $(build.buildNumber)

    workingDirectory: tools\$(build.projectName)
    displayName: Build and Push Package